Added resource model
beyond-io/tutor pull request #44
Opened 2020-09-13 13:17 UTC by LiorRey

Relating to #36

Added an SQLAlchemy table/class for handling the data of a resource of a course.

2020-09-14 08:03 UTC, mosesnagar requested changes

2020-09-14 09:49 UTC, LiorRey commented on tutor/models/resource.py
> +    course_id = db.Column(db.Integer, db.ForeignKey(course.id), nullable=False)
> The `db. ForeignKey` parameter should be a string, isn't it?

at line 10:
It should be the Primary Key of the specific user who posted the resource. And if the id field of the user was declared as an Integer - ForeignKey should be an Integer.

at line 11:
It should be the Primary Key of the specific course for which the resource was posted - which I declared as an Integer, hence ForeignKey is also an Integer.

2020-09-14 11:37 UTC, mosesnagar commented on tutor/models/resource.py
> +    course_id = db.Column(db.Integer, db.ForeignKey(course.id), nullable=False)
For line 10: we have no users yet.

For line 11: Agree, but there is no `course` object(or dict) to get `id` property(or key) from. Taken from SQLAlchemy docs: 
![image](https://user-images.githubusercontent.com/16582718/93080770-ea9e6d80-f696-11ea-9f8e-9ee1d2031a60.png)
But if you checked it and there are no problems I think it's fine.

2020-09-15 06:26 UTC, ifireball commented
Is this a dependency of PR #45 ? Its not mentioned there...

2020-09-17 11:54 UTC, bardielle commented
@LiorRey What about that PR?

2020-09-21 12:54 UTC, LiorRey commented
> @LiorRey What about that PR?

2020-09-21 12:54 UTC, closed without merging