selecting specific flake8 tests
beyond-io/tutor pull request #55
Opened 2020-09-17 21:29 UTC by Michal-Shamir

2020-09-17 22:13 UTC, mosesnagar approved these changes
I think it's a good choice of errors to search for.

2020-09-21 11:56 UTC, lioramilbaum requested changes
CI is still broken. First fix the CI. It is not custom to ask for a review when CI is broken.

2020-09-21 14:44 UTC, Michal-Shamir commented
all checks passed now

2020-09-21 14:48 UTC, lioramilbaum approved these changes

2020-09-21 14:50 UTC, merged